# Generated by Django 4.2.4 on 2023-08-08 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_created_task_important'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created',
        ),
        migrations.RemoveField(
            model_name='task',
            name='important',
        ),
    ]
